In [67]:
#Lecture 3 - Lists vs Arrays

In [68]:
import numpy as np

In [69]:
L = [1,2,3]

In [70]:
A = np.array([1,2,3])

In [71]:
for e in L:
    print (e)

1
2
3


In [72]:
for e in A:
    print(e)

1
2
3


In [78]:
L.append(4) ## add to the end of the list 

In [79]:
#L

In [80]:
#A.append doesnt work as you cant append a array liek this 

In [81]:
###append with concatenation
L = L+[5]

In [82]:
L ### the number concatenation worked 

[1, 2, 3, 4, 5]

In [36]:
#A= A+[4] ## this does work but not in the intended manner 

In [37]:
#print(A)

In [85]:
L2 = []

In [86]:
for e in L:
    L2.append(e+e)

In [87]:
L2

[2, 4, 6, 8, 10]

In [88]:
A+A

array([2, 4, 6])

In [89]:
A

array([1, 2, 3])

In [90]:
#A + with lists does concatenation 
#+ with Arrays does vector addition 
#if it was a matrix i.e a 2d array it would do matrix addition 

In [91]:
2*A ##this is a vector operation 

array([2, 4, 6])

In [92]:
2*L   #repeats the list 2 times 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [93]:
#L**2 ## this doesnt work with lists 

In [94]:
###if you want to do the above you need to do it woth a for loop 
L2=[]

for e in L:
    L2.append(e*e)
    
print(L2)

[1, 4, 9, 16, 25]


In [95]:
print (L)


[1, 2, 3, 4, 5]


In [96]:
A**2

array([1, 4, 9])

In [97]:
np.sqrt(A) ###learn more about square roots...cant remember from school 

array([ 1.        ,  1.41421356,  1.73205081])

In [98]:
np.log(A) ###what does the log do?

array([ 0.        ,  0.69314718,  1.09861229])

In [99]:
np.exp(A) #Learn more about explonentials 


###

array([  2.71828183,   7.3890561 ,  20.08553692])

In [100]:
####if you wanted to do the more complex commands mentions i.e log sqrt and exp you woulf have to do these witha for loop in lists 
###vectors and matrix arrays are much more convienient 

In [101]:
##for loops are very slow and you should avoid them with doing math operations 

In [102]:
###Need to do the prerequisites before doing the course

#Lecture 4 dot products 

##what is a dot product 

In [103]:
import scipy